### ISSUE TITLE
Miscellaneous errors in the test programs

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/hyperseti#44]
Small fixes to test_data_array.py, test_datwrapper.py, and test_kurtosis.py are needed.  Fixed in PR #45.

Still, there is an outstanding error in test_hyperseti.py, line 39:
assert np.max(dedopp.data) == np.sum(test_data[:, :, 511])

```
python3 test_hyperseti.py
bshuf filter already loaded, skip it.
lz4 filter already loaded, skip it.
zfp filter already loaded, skip it.
type(dedopp): <class 'hyperseti.data_array.DataArray'>
dedopp.data: [[[5.4800777 5.656854  5.656854  ... 5.656854  5.656854  5.656854 ]]

 [[5.4800777 5.656854  5.656854  ... 5.656854  5.656854  5.656854 ]]

 [[5.4800777 5.656854  5.656854  ... 5.656854  5.656854  5.656854 ]]

 ...

 [[5.4800777 5.656854  5.656854  ... 5.4800777 5.4800777 5.4800777]]

 [[5.4800777 5.656854  5.656854  ... 5.4800777 5.4800777 5.4800777]]

 [[5.4800777 5.656854  5.656854  ... 5.4800777 5.4800777 5.4800777]]]
np.max(dedopp.data): 56.568542 , np.sum(test_data[:, :, 511]): 320.0
Traceback (most recent call last):
  File "test_hyperseti.py", line 283, in <module>
    test_dedoppler()
  File "test_hyperseti.py", line 39, in test_dedoppler
    assert np.max(dedopp.data) == np.sum(test_data[:, :, 511])
AssertionError
```

Clearly there is a mismatch between ```dedopp.data``` and the raw ```test_data```.

**Comment by texadactyl** [comment]
Same issue using the notebook, try_hyperseti.ipynb

**Comment by texadactyl** [comment]
The only errors left are the following assertions:
```
FAILED test/test_hyperseti.py::test_dedoppler - assert array(56.5685...dtype=float32) == 320.0
FAILED test/test_hyperseti.py::test_dedoppler_boxcar - assert 40.0 == 160.0
FAILED test/test_hyperseti.py::test_hitsearch - assert 7750.55322265625 == 32000.0
```
