### ISSUE TITLE
Package cusignal cannot be installed in the Seti BL data centre

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/hyperseti#67]
On the data centre nodes, it might be the old Ubuntu (16.04), the old Python (3.7.3), the old cupy (8.6.0), .....

pip install cusignal -U --user
```
Collecting cusignal
  Using cached cusignal-0.0.1.tar.gz (1.1 kB)
Building wheels for collected packages: cusignal
  Building wheel for cusignal (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lrd2aspr/cusignal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lrd2aspr/cusignal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8dmsf5fo
       cwd: /tmp/pip-install-lrd2aspr/cusignal/
  Complete output (25 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-lrd2aspr/cusignal/setup.py", line 35, in <module>
      cmdclass={'install': InstallWrapper},
    File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-lrd2aspr/cusignal/setup.py", line 15, in run
      raise Exception(long_description)
  Exception: Please install cusignal via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.
  ----------------------------------------
  ERROR: Failed building wheel for cusignal
  Running setup.py clean for cusignal
Failed to build cusignal
Installing collected packages: cusignal
    Running setup.py install for cusignal ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lrd2aspr/cusignal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lrd2aspr/cusignal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xpppzdwd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/texadactyl/.local/include/python3.7m/cusignal
         cwd: /tmp/pip-install-lrd2aspr/cusignal/
    Complete output (16 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lrd2aspr/cusignal/setup.py", line 35, in <module>
        cmdclass={'install': InstallWrapper},
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-lrd2aspr/cusignal/setup.py", line 15, in run
        raise Exception(long_description)
    Exception: Please install cusignal via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lrd2aspr/cusignal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lrd2aspr/cusignal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xpppzdwd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/texadactyl/.local/include/python3.7m/cusignal Check the logs for full command output.
```

**Comment by mattlebofsky** [comment]
Were you trying to install this in the conda "base" environment? Or some other environment?

**Comment by texadactyl** [comment]
I was running this:

**Comment by texadactyl** [comment]
In my .profile: ```source source /opt/conda/init.sh```

**Comment by texadactyl** [comment]
cusignal is installed automatically because it is mentioned in ```requirements.txt```

**Comment by texadactyl** [comment]
Will leave cusignal as a conda install in the hyperseti environment.
